// @flow
export const ACTION_LOADING_START = "ACTION_LOADING_START";
export const ACTION_LOADING_STOP = "ACTION_LOADING_STOP";
export const ACTION_SHOW_ERROR = "ACTION_SHOW_ERROR";

export const ACTION_LOAD_ALL_SONGS = "ACTION_LOAD_ALL_SONGS";
export const ACTION_LOAD_ALL_PLAYLISTS = "ACTION_LOAD_ALL_PLAYLISTS";
export const ACTION_CHANGE_DISPLAYING_PLAYLIST = "ACTION_CHANGE_DISPLAYING_PLAYLIST";
export const ACTION_CHANGE_PLAYING_NOW = "ACTION_CHANGE_PLAYING_NOW";

export const ACTION_TYPE_SHOW_SONG_OPERATION_MODAL = "ACTION_TYPE_SHOW_SONG_OPERATION_MODAL";
export const ACTION_TYPE_HIDE_SONG_OPERATION_MODAL = "ACTION_TYPE_HIDE_SONG_OPERATION_MODAL";

export const ACTION_TYPE_SHOW_ADD_TO_PLAYLIST_MODAL = "ACTION_TYPE_SHOW_ADD_TO_PLAYLIST_MODAL";
export const ACTION_TYPE_HIDE_ADD_TO_PLAYLIST_MODAL = "ACTION_TYPE_HIDE_ADD_TO_PLAYLIST_MODAL";

export const ACTION_LOGIN = "ACTION_LOGIN";
export const ACTION_LOGOUT = "ACTION_LOGOUT";