// @flow
export const ACTION_LOAD_ALL_SONGS = "ACTION_LOAD_ALL_SONGS";
export const ACTION_LOADING_START = "ACTION_LOADING_START";
export const ACTION_LOADING_STOP = "ACTION_LOADING_STOP";
export const ACTION_SHOW_ERROR = "ACTION_SHOW_ERROR";
export const ACTION_CHANGE_PLAYING_NOW = "ACTION_CHANGE_PLAYING_NOW";
